version: '3.5'

services:
  app:
    # image: smartdogstudio/sds-php-8.1:1.0
    build:
      context: ./docker
      dockerfile: runtime.7.3.Dockerfile
    container_name: sistemas_ipduv-php
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db

  server:
    image: nginx:alpine
    container_name: sistemas_ipduv-nginx
    ports:
      - 8003:80
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/app
    working_dir: /app
    depends_on:
      - app
  db:
    image: mariadb:10.7
    container_name: sistemas_ipduv-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - maria-data:/var/lib/mysql
    ports:
      - 3310:3306

volumes:
  maria-data:
    driver: local
